// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// fastq_AT
Rcpp::NumericVector fastq_AT(std::string fq_path, bool gz, size_t nreads);
RcppExport SEXP _WhatToExpect_fastq_AT(SEXP fq_pathSEXP, SEXP gzSEXP, SEXP nreadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type fq_path(fq_pathSEXP);
    Rcpp::traits::input_parameter< bool >::type gz(gzSEXP);
    Rcpp::traits::input_parameter< size_t >::type nreads(nreadsSEXP);
    rcpp_result_gen = Rcpp::wrap(fastq_AT(fq_path, gz, nreads));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_WhatToExpect_fastq_AT", (DL_FUNC) &_WhatToExpect_fastq_AT, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_WhatToExpect(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
